workspace:
  base: /go
  path: src/github.com/cloud104/kube-db

pipeline:
  # test:
  #   image: golang:alpine
  #   group: build
  #   commands:
  #     - CGO_ENABLED=0 GOOS=linux GO111MODULE=on go test ./...

  build:
    image: golang
    group: build
    commands:
      - GOOS=linux CGO_ENABLED=0 GO111MODULE=on go build

  publish-feature:
    image: plugins/docker
    group: deploy
    repo: quay.io/cloud104/${DRONE_REPO_NAME}
    secrets: [ docker_username, docker_password ]
    environment:
      - DOCKER_REGISTRY=quay.io
    tags:
      - "latest"
      - ${DRONE_BRANCH/\//-}-${DRONE_BUILD_NUMBER}
    when:
      branch:
        include: [ feature/*, hotfix/* ]

  tag:
    image: cloud104/drone-github-tag
    secrets: [ plugin_github_token ]
    when:
      branch:
        include: [ develop ]

  publish:
    image: plugins/docker
    group: deploy
    repo: quay.io/cloud104/${DRONE_REPO_NAME}
    secrets: [ docker_username, docker_password ]
    environment:
      - DOCKER_REGISTRY=quay.io
    auto_tag: true
    when:
      event: tag

  chart:
    image: cloud104/drone-chartmuseum
    group: deploy
    chart_path: hack/helm
    secrets: [ plugin_repo_username, plugin_repo_password, plugin_repo_url ]

  slack:
    image: plugins/slack
    username: ${DRONE_REPO_NAME}
    secrets: [ plugin_webhook ]
