dist: trusty
sudo: required
language: go
go: "1.10"
services:
  - docker
install:
  - GOOS=linux CGO_ENABLED=0 go build
  - go test

after_success:
  - scripts/deploy.sh

notifications:
  email: false
