dist: trusty
sudo: required
language: go
go: "1.12"
services:
  - docker
install:
  - GOOS=linux CGO_ENABLED=0 GO111MODULE=on go build
  - go test

after_success:
  - hack/scripts/deploy.sh

notifications:
  email: false
