apiVersion: v1
kind: Secret
metadata:
  name: k8s-rds
type: Opaque
data:
  mykey: cGFzc3dvcmRvcnNvbWV0aGluZw==
---
apiVersion: k8s.io/v1
kind: Database
metadata:
  name: mypgsql
  namespace: default
spec:
  class: db.t2.medium
  engine: postgres
  dbname: thepgsql
  name: thatpgsql
  password:
    key: mykey
    name: k8s-rds
  username: postgres
  size: 10
