version: "3.7"
services:
  test:
    image: golang
    entrypoint: ""
    working_dir: /go/src/github.com/cloud104/kube-db
    command: go test
    volumes:
      - .:/go/src/github.com/cloud104/kube-db
  vault:
    image: vault
    ports:
      - 8200:8200
    volumes:
      - vault:/vault/file
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=tks
    cap_add:
      - IPC_LOCK
volumes:
  vault: {}
