apiVersion: v1
kind: Secret
metadata:
  name: {{ template "k8s-rds.shortname" . }}
data:
{{- range $key, $val := .Values.secrets }}
  {{ $key | lower }}: {{ $val | b64enc | quote }}
{{- end }}
---
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.image.pullSecret }}
kind: Secret
metadata:
  name: {{ include "k8s-rds.shortname" . }}-image-pull-secret
type: kubernetes.io/dockerconfigjson
