apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-db-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-db-manager-role
subjects:
- kind: User
  name: system:serviceaccount:kube-db-system:kube-db
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-db-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-db-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
