---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-db.fullname" . }}-config
stringData:
  config.yaml: 'foo: bar'
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-db.fullname" . }}
data:
{{- range $key, $val := .Values.secrets }}
  {{ $key | lower }}: {{ $val | b64enc | quote }}
{{- end }}
