---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-db.fullname" . }}-config
stringData:
  config.yaml: ''
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-db.fullname" . }}
data:
{{- range $key, $val := .Values.secrets }}
  {{ $key | lower }}: {{ $val | b64enc | quote }}
{{- end }}
---
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.image.pullSecret }}
kind: Secret
metadata:
  name: {{ include "kube-db.fullname" . }}-image-pull-secret
type: kubernetes.io/dockerconfigjson
