apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: kube-db-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: kube-db-controller-manager-service
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      imagePullSecrets:
      - name: {{ include "kube-db.fullname" . }}-image-pull-secret
      # initContainers:
      # - name: vault-authenticator
      #   image: sethvargo/vault-kubernetes-authenticator:0.2.0
      #   imagePullPolicy: Always
      #   volumeMounts:
      #   - name: vault-auth
      #     mountPath: /var/run/secrets/vaultproject.io
      #   env:
      #   - name: VAULT_ROLE
      #     value: myapp-role
      #   securityContext:
      #     allowPrivilegeEscalation: false
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --metrics-addr=127.0.0.1:8080
        command:
        - /manager
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        env: {{- include "kube-db.env" . | nindent 8 }}
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /home/vault
          name: secret
          readOnly: true
      terminationGracePeriodSeconds: 10
      serviceAccountName: {{ include "kube-db.fullname" . }}
      volumes:
      - emptyDir:
          medium: Memory
        name: vault-auth
      - emptyDir:
          medium: Memory
        name: vault-secrets
      - name: secret
        secret:
          secretName: {{ template "kube-db.fullname" . }}-config
