apiVersion: v1
kind: Secret
metadata:
  name: c12345-name
type: Opaque
data:
  password: cGFzc3dvcmRvcnNvbWV0aGluZw==
---
apiVersion: k8s.io/v1
kind: Database
metadata:
  name: c12345-name
spec:
  class: db.t2.micro
  dbname: testdb
  engine: postgres
  instanceIdentifier: c12345-test
  size: 10
  subnetGroupName: private
  username: postgres
  password:
    key: password
    name: c12345-name
